version: '3'

services:
  jdservice:
    build: JD-service/
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  jdproxy:
    build: JD-proxy/
    depends_on:
      - 'database'
      - 'jdservice'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest